#!/bin/sh

# This script is a part of Rbook package.
# It's purpose is to encode sound stream coming to the standard input
# to mp3.
#
# -f <value> -- Sampling frequency of the original sound stream in kHz.
# -b <value> -- Average bitrate in VBR mode.
# -c <value> -- Bitrate in CBR mode.
# -v <value> -- Volume scale factor.

# Output file name must be determined in the command line.

# Clear variables:
freq=10000
volume=1.0
bitrate=

# Command line parsing:
while test "$1"; do
    case "$1" in
        -f) shift
            freq=$1
            ;;
        -b) shift
            bitrate="--vbr-new -V 0 --abr $1"
            ;;
        -c) shift
            bitrate="-F -q 0 -b $1"
            ;;
        -v) shift
            volume=$1
            ;;
        *) file="$1"
            ;;
    esac
    shift
done

exec 2>&1 >/dev/null

# Do the job
exec sox -G -D -t raw -e signed-integer -b 8 -r "$freq" -v "$volume" - -t wav -b 16 -r 16000 - rate | lame -m m $bitrate - "$file"
