#!/bin/sh

# This script is a part of Rbook package.
# It's purpose is to encode sound stream coming to the standard input
# to mp3.
#
# -f <value> -- Sampling frequency of the original sound stream in kHz.
# -b <value> -- Wanted bitrate.
# -v <value> -- Volume scale factor.

# Output file name must be determined in the command line.

# Clear variables:
freq=10000
bitrate=32
volume=1.0

# Command line parsing:
while test $1; do
    case $1 in
        -f) shift
            freq=$1
            ;;
        -b) shift
            bitrate=$1
            ;;
        -v) shift
            volume=$1
            ;;
        *) file=$1
            ;;
    esac
    shift
done

exec 2>&1 >/dev/null

# Use VBR
#exec sox -t raw -s -1 -r $freq - -t wav -2 -r 16000 - rabbit | lame -S -m m --scale "$volume" --vbr-new -V 0 --abr "$bitrate" - "$file"

# For hardware players
exec sox -t raw -s -1 -r $freq - -t wav -2 -r 16000 - rabbit | lame -m m --scale "$volume" -b "$bitrate" -F -q 0 - "$file"
