#!/bin/sh

# This script is a part of Rbook package.
# It's purpose is to generate and play audible speech
# from the text which comes to standard input.
#
# The flag "-s" followed by a number means silence
# for the requested number of hundredth of second.
# -v <value> -- Set speech volume. Value must be between 0 and 1.
# -p <value> -- Set pitch. Value must be between 0 and 1.
# -r <value> -- Set speech rate. Value must be between 0 and 1.
# -f <value> defines treatment of sampling frequency in Hz.
# -n -- Don't play generated sound stream.
# Return it as a standard output instead.
# -l <filename> -- Collect unknown words in specified file.
# -d <filename> -- Use specified pronunciation dictionary.

# Variables initialization:
pitch=
rate=
freq=
dict=
collect=

# Commands to use for actual tasks accomplishing:
sndgen='ru_tts $pitch $rate $dict $collect'
sndplay='aplay -q -t raw -f S8 -r $freq 2>/dev/null'

# Command line parsing:
while test $1; do
    case $1 in
        -s) shift
            length=$1
            sndgen='dd if=/dev/zero bs=`expr $freq / 100` count=$length'
            ;;
        -v) shift
            VOLUME=$1
            ;;
        -p) shift
            pitch="-p $1"
            ;;
        -r) shift
            rate="-r $1"
            ;;
        -f) shift
            freq=$1
            ;;
        -n) sndplay='sox -q -t raw -s -1 -r $freq - -t raw -s -2 -r 16000 -'
            ;;
        -l) shift
            collect="-l $1"
            ;;
        -d) shift
            dict="-s $1"
            ;;
        *) ;;
    esac
    shift
done

# Do the job.
exec 2>/dev/null
eval "exec $sndgen | $sndplay"
