#!/bin/sh

# This script is a part of Rbook package.
# It's purpose is to generate and play audible speech
# from the text which comes to standard input.
#
# The flag "-s" followed by a number means silence
# for the requested number of hundredth of second.
# -v <value> -- Set speech volume. Value must be between 0 and 1.
# -p <value> -- Set pitch. Value must be between 0 and 1.
# -r <value> -- Set speech rate. Value must be between 0 and 1.
# -f <value> defines treatment of sampling frequency in Hz.
# -n -- Don't play generated sound stream.
# Return it as a standard output instead.

# Default values of speech parameters:
VOLUME=0.8
FREQUENCY=10300
RATE=0.0
PITCH=0.0

# Commands to use for actual tasks accomplishing:
sndgen='ru_tts -p $PITCH -r $RATE -s /usr/local/lib/ru_tts/lexicon'
sndplay='sox -t raw -s -b -r $FREQUENCY -c 1 -v $VOLUME - -t ossdsp -c 2 -w /dev/dsp'

# Command line parsing:
while test $1
do case $1 in
     -s) shift
         length=$1
         sndgen='dd if=/dev/zero bs=`expr $FREQUENCY / 100` count=$length'
         ;;
     -v) shift
         VOLUME=$1
         ;;
     -p) shift
         PITCH=$1
         ;;
     -r) shift
         RATE=$1
         ;;
     -f) shift
         FREQUENCY=$1
         ;;
     -n) sndplay='sox -t raw -s -b -r $FREQUENCY -c 1 -v $VOLUME - -t raw -u -'
         ;;
      *) ;;
   esac
   shift
done

# Do the job.
exec 2>/dev/null
eval "exec $sndgen | $sndplay"
