#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/rbook

FLAVOR=$1
PACKAGE=rbook

echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}

if [ ${FLAVOR} = emacs ]; then
    rm -f /usr/share/${FLAVOR}/site-lisp/${PACKAGE}/*.elc
else
    rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
fi
