#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/rbook

FLAVOR=$1
PACKAGE=rbook

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

case "$FLAVOR" in
    xemacs*)
        SITEFLAG="-no-site-file"
        ;;
    emacs*)
        SITEFLAG="--no-site-file"
        ;;
    *)
        echo "unknown flavor $FLAVOR, does not start with emacs or xemacs"
	exit 1
        ;;
esac

FLAGS="${SITEFLAG} -q -batch -l path.el -f batch-byte-compile"
ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}

install -m 755 -d ${ELCDIR}
cd ${ELDIR}
src=`echo *.el`
cd ${ELCDIR}

if [ ${FLAVOR} != emacs ]; then
    for file in $src
    do ln -s ../../../emacs/site-lisp/${PACKAGE}/$file
    done
fi

cat << EOF > path.el
(setq load-path (cons "." load-path) byte-compile-warnings nil)
EOF
${FLAVOR} ${FLAGS} ${src}
rm -f path.el

exit 0
